[[custom_groups]]
name = 'ğŸ­ Proxy'
type = "select"
rule = ['[]ğŸ’ HongKong', '[]ğŸ€ Taiwan', '[]ğŸµ Singapore', '[]ğŸŒ¹ U.S.', '[]ğŸŒ¸ Japan', '[]â˜€ï¸ DIRECT', '(^[^1-9].*)']

[[custom_groups]]
name = 'ğŸ’§ Telegram'
type = "select"
rule = ['[]ğŸµ Singapore','[]ğŸ’ HongKong','[]ğŸ€ Taiwan','[]ğŸ­ Proxy','(æ–°åŠ å¡.*?[x\\d\\)]$|SGP.*?[x\\d\\)]$)','[]â˜€ï¸ DIRECT'
]

[[custom_groups]]
name = 'ğŸ– OpenAI'
type = "select"
rule = ['[]ğŸµ Singapore', '[]ğŸŒ¹ U.S.', '[]ğŸŒ¸ Japan', '[]ğŸ­ Proxy', '(æ–°åŠ å¡.*?[x\d\)]$|SGP.*?[x\d\)]$|ç¾å›½.*?[x\d\)]$|USA.*?[x\d\)]$|æ—¥æœ¬.*?[x\d\)]$|JP.*?[x\d\)]$)']

[[custom_groups]]
name = 'âš¡ï¸ Google'
type = "select"
rule = ['[]ğŸ’ HongKong', '[]ğŸ€ Taiwan', '[]ğŸŒ¸ Japan', '[]ğŸµ Singapore', '[]ğŸŒ¹ U.S.', '[]ğŸ­ Proxy', '(^[^1-9].*)']

[[custom_groups]]
name = 'âœ¨ YouTube'
type = "select"
rule = ['[]ğŸ’ HongKong', '[]ğŸŒ¹ U.S.', '[]ğŸµ Singapore', '[]ğŸŒ¸ Japan', '[]ğŸ­ Proxy', '(^[^1-9].*)', '[]â˜€ï¸ DIRECT']

[[custom_groups]]
name = 'ğŸŒŸ GlobalMedia'
type = "select"
rule = ['[]ğŸ­ Proxy', '[]â˜€ï¸ DIRECT', '(^[^1-9].*)']

[[custom_groups]]
name = 'â˜„ï¸ Others'
type = "select"
rule = ['[]ğŸ­ Proxy', '[]â˜€ï¸ DIRECT', '(^[^1-9].*)']

[[custom_groups]]
name = 'ğŸŒ¹ U.S.'
type = "select"
rule = ['[]ğŸŒ¹ url-test', '(ç¾å›½.*?[x\d\)]$|USA.*?[x\d\)]$)']

[[custom_groups]]
name = 'ğŸ’ HongKong'
type = "select"
rule = ['[]ğŸ’ url-test', '(é¦™æ¸¯.*?[x\d\)]$|HK.*?[x\d\)]$)']

[[custom_groups]]
name = 'ğŸ€ Taiwan'
type = "select"
rule = ['[]ğŸ€ url-test', '(å°æ¹¾.*?[x\d\)]$|TW.*?[x\d\)]$)']

[[custom_groups]]
name = 'ğŸµ Singapore'
type = "select"
rule = ['[]ğŸµ url-test', '(æ–°åŠ å¡.*?[x\d\)]$|SGP.*?[x\d\)]$)']

[[custom_groups]]
name = 'ğŸŒ¸ Japan'
type = "select"
rule = ['[]ğŸŒ¸ url-test', '(æ—¥æœ¬.*?[x\d\)]$|JP.*?[x\d\)]$)']

[[custom_groups]]
name = 'ğŸŒ¹ url-test'
type = "url-test"
rule = ['(ç¾å›½.*?[x\d\)]$|USA.*?[x\d\)]$)']
url = 'http://www.gstatic.com/generate_204'
interval = 400

[[custom_groups]]
name = 'ğŸ’ url-test'
type = "url-test"
rule = ['(é¦™æ¸¯.*?[x\d\)]$|HK.*?[x\d\)]$)']
url = 'http://www.gstatic.com/generate_204'
interval = 400

[[custom_groups]]
name = 'ğŸ€ url-test'
type = "url-test"
rule = ['(å°æ¹¾.*?[x\d\)]$|TW.*?[x\d\)]$)']
url = 'http://www.gstatic.com/generate_204'
interval = 400

[[custom_groups]]
name = 'ğŸµ url-test'
type = "url-test"
rule = ['(æ–°åŠ å¡.*?[x\d\)]$|SGP.*?[x\d\)]$)']
url = 'http://www.gstatic.com/generate_204'
interval = 400

[[custom_groups]]
name = 'ğŸŒ¸ url-test'
type = "url-test"
rule = ['(æ—¥æœ¬.*?[x\d\)]$|JP.*?[x\d\)]$)']
url = 'http://www.gstatic.com/generate_204'
interval = 400

[[custom_groups]]
name = 'ğŸ’¥ ADban'
type = "select"
rule = ['[]REJECT', '[]â˜€ï¸ DIRECT']

[[custom_groups]]
name = 'â˜€ï¸ DIRECT'
type = "select"
rule = ['[]DIRECT']
