[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/Ohhu/Links/Profiles/DIRECT.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

[[rulesets]]
group = "ğŸ’¥ ADban"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "ğŸ’¥ ADban"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"

[[rulesets]]
group = "ğŸ­ Proxy"
ruleset = "https://raw.githubusercontent.com/Ohhu/Links/Profiles/Proxy.list"

[[rulesets]]
group = "ğŸ– OpenAI"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"

[[rulesets]]
group = "âœ¨ YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸŒŸ GlobalMedia"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "âš¡ï¸ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list"

[[rulesets]]
group = "ğŸ’§ Telegram"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ­ Proxy"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

[[rulesets]]
group = "âš¡ï¸ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Google.list"

[[rulesets]]
group = "ğŸ’§ Telegram"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ­ Proxy"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

[[rulesets]]
group = "â˜„ï¸ Others"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Others.list"
